"""prepare domain models for phase 3 ingestion

Revision ID: d911d2b457ed
Revises: 'b1384c16cb09'
Create Date: 2026-09-17 14:26:47.674406

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d911d2b457ed"
down_revision: str | None = "b1384c16cb09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issues",
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "issues",
        "key",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "issues",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.add_column(
        "pull_requests",
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "pull_requests",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "repositories",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "repositories",
        "full_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "repositories",
        "full_name",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "repositories",
        "name",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "pull_requests",
        "title",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("pull_requests", "closed_at")
    op.alter_column(
        "issues",
        "title",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "issues",
        "key",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("issues", "provider_updated_at")
    # ### end Alembic commands ###
